FROM python:3.11-slim
WORKDIR /app
RUN pip install --no-cache-dir torch --index-url https://download.pytorch.org/whl/cpu
RUN pip install --no-cache-dir monai nibabel numpy fastapi uvicorn python-multipart matplotlib
EXPOSE 8000
CMD ["uvicorn", "serve_api:app", "--host", "0.0.0.0", "--port", "8000"]
